
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Regi
 */
public class DocentenTab extends javax.swing.JPanel {

    /**
     * Creates new form DocentenTab
     */
    public DocentenTab() {
        initComponents();
        fillSelecteerDocentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        lijstDocenten = new javax.swing.JList();
        docentZoekField2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        docentVoornaamField = new javax.swing.JTextField();
        docentStraatField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        docentPostcodeField = new javax.swing.JTextField();
        docentAchternaamField = new javax.swing.JTextField();
        docentHuisnummerField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        docentPlaatsField = new javax.swing.JTextField();
        docentVastField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        docentEmailField = new javax.swing.JTextField();
        docentMobielField = new javax.swing.JTextField();
        docentWijzigButton = new javax.swing.JButton();
        docentZoekButton = new javax.swing.JButton();
        docentZoekField1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        docentRekeningField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        docentZoekCombo = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        docentToevoegButton = new javax.swing.JButton();
        docentTussenVoegselField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        docentZoekField3 = new javax.swing.JTextField();

        lijstDocenten.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "--Nieuwe Speler--", "Piet Pieterson", "Henk Henkstra" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lijstDocenten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lijstDocentenMouseClicked(evt);
            }
        });
        lijstDocenten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lijstDocentenValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(lijstDocenten);

        jLabel34.setText("Straat");

        jLabel35.setText("Telefoon - Thuis");

        jLabel33.setText("Voornaam");

        jLabel36.setText("Telefoon - Mobiel");

        jLabel37.setText("Email");

        docentAchternaamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentAchternaamFieldActionPerformed(evt);
            }
        });

        docentHuisnummerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentHuisnummerFieldActionPerformed(evt);
            }
        });

        jLabel43.setText("Huisnr");

        docentPlaatsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentPlaatsFieldActionPerformed(evt);
            }
        });

        jLabel44.setText("Plaats");

        docentWijzigButton.setText("Wijzig");
        docentWijzigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentWijzigButtonActionPerformed(evt);
            }
        });

        docentZoekButton.setText("Zoek op");
        docentZoekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentZoekButtonActionPerformed(evt);
            }
        });

        jLabel38.setText("Rekeningnummer");

        jLabel40.setText("Postcode");

        docentZoekCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Naam" }));
        docentZoekCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentZoekComboActionPerformed(evt);
            }
        });

        jLabel41.setText("Tussenvoegsel");

        docentToevoegButton.setText("Voeg docent toe");
        docentToevoegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentToevoegButtonActionPerformed(evt);
            }
        });

        jLabel42.setText("Achternaam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel40)
                            .addComponent(docentPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(docentHuisnummerField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(docentPlaatsField)))
                    .addComponent(docentVastField)
                    .addComponent(docentMobielField)
                    .addComponent(docentEmailField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(docentVoornaamField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(docentTussenVoegselField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel41)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(0, 183, Short.MAX_VALUE))
                                    .addComponent(docentAchternaamField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(docentWijzigButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(docentToevoegButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(docentZoekButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(docentZoekCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(docentZoekField3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(docentZoekField2)
                                            .addComponent(docentZoekField1)))
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(docentStraatField)
                            .addComponent(docentRekeningField))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docentVoornaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentTussenVoegselField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentAchternaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(docentStraatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docentPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentHuisnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentPlaatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(docentVastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(docentMobielField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(docentEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(docentRekeningField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docentWijzigButton)
                            .addComponent(docentToevoegButton))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docentZoekCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentZoekField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docentZoekButton))
                        .addGap(7, 7, 7)
                        .addComponent(docentZoekField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(docentZoekField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lijstDocentenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lijstDocentenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lijstDocentenMouseClicked

    private void lijstDocentenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lijstDocentenValueChanged
        if (lijstDocenten.getSelectedValue() != null && lijstDocenten.getSelectedValue() instanceof Docent) {
            fillDocentFields((Docent)lijstDocenten.getSelectedValue());
            docentWijzigButton.setEnabled(true);
            docentToevoegButton.setEnabled(false);
        }
        else if (lijstDocenten.getSelectedIndex() == 0 || lijstDocenten.getSelectedValue() == null) {
            docentWijzigButton.setEnabled(false);
            docentToevoegButton.setEnabled(true);
            resetDocentFields();
            
        } 
        
    }//GEN-LAST:event_lijstDocentenValueChanged

    private void docentAchternaamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentAchternaamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docentAchternaamFieldActionPerformed

    private void docentHuisnummerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentHuisnummerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docentHuisnummerFieldActionPerformed

    private void docentPlaatsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentPlaatsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docentPlaatsFieldActionPerformed

    private void docentWijzigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentWijzigButtonActionPerformed
        wijzigenDocent();
    }//GEN-LAST:event_docentWijzigButtonActionPerformed

    private void docentZoekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentZoekButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docentZoekButtonActionPerformed

    private void docentZoekComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentZoekComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docentZoekComboActionPerformed

    private void docentToevoegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentToevoegButtonActionPerformed
        toevoegenDocent();
    }//GEN-LAST:event_docentToevoegButtonActionPerformed
    private void resetDocentFields()
    {
       docentVoornaamField.setText(null);
        docentTussenVoegselField.setText(null);
        docentAchternaamField.setText(null);
        docentStraatField.setText(null);
        docentHuisnummerField.setText(null);
        docentPostcodeField.setText(null);
        docentPlaatsField.setText(null);
        docentEmailField.setText(null);
        docentVastField.setText(null);
        docentMobielField.setText(null);
        docentRekeningField.setText(null);  
    }
    private void fillDocentFields(Docent docent) {
        docentVoornaamField.setText(docent.getVoornaam());
        docentTussenVoegselField.setText(docent.getTussenvoegsel());
        docentAchternaamField.setText(docent.getAchternaam());
        docentStraatField.setText(docent.getStraat());
        docentHuisnummerField.setText(docent.getHuisnummer());
        docentPostcodeField.setText(docent.getPostcode());
        docentPlaatsField.setText(docent.getWoonplaats());
        docentEmailField.setText(docent.getEmail());
        docentVastField.setText(docent.getVNR());
        docentMobielField.setText(docent.getMNR());
        docentRekeningField.setText((docent.getRekening()));
    }

    private ArrayList<Docent> getDocenten() {
        String query = "SELECT docent_nr FROM docent;";
        ArrayList<Docent> docenten = new ArrayList();
        try {
            Connection conn = FullHouseDatabase.getConnection();
            Statement stat = conn.createStatement();
            ResultSet result = stat.executeQuery(query);

            
            while (result.next()) {
                docenten.add(new Docent(result.getInt("docent_nr")));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        return docenten;
    }

    private void wijzigenDocent() {
        boolean valid = true;
        if (lijstDocenten.getSelectedValue() instanceof Docent) {
            Docent selectedDocent = (Docent) lijstDocenten.getSelectedValue();
            if (selectedDocent.existsInDB()) {
                selectedDocent.setAdres(docentStraatField.getText(), docentHuisnummerField.getText(), docentPlaatsField.getText(), docentPostcodeField.getText());
                selectedDocent.setNaam(docentVoornaamField.getText(), docentTussenVoegselField.getText(), docentAchternaamField.getText());
                selectedDocent.setContactGegevens(docentVastField.getText(), docentMobielField.getText(), docentEmailField.getText());
                try {
                    String rekening = docentRekeningField.getText();
                    selectedDocent.setRekening(rekening);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Rekening moet een getal zijn!");
                    valid = false;
                }
            }
            if (valid) {
                selectedDocent.writeToDB();
            }
        }
    }

    private void toevoegenDocent() {
        String voornaam = docentVoornaamField.getText();
        String tussenVoegsel = docentTussenVoegselField.getText();
        String achternaam = docentAchternaamField.getText();
        String straat = docentStraatField.getText();
        String huisnummer = docentHuisnummerField.getText();
        String postcode = docentPostcodeField.getText();
        String plaats = docentPlaatsField.getText();
        String mobiel = docentMobielField.getText();
        String vast = docentVastField.getText();
        String email = docentEmailField.getText();
        String rekening = "";
        boolean valid = true;
        try {
            rekening = docentRekeningField.getText();
        } catch (NumberFormatException e) {
            System.out.println(e);
            valid = false;
        }

        if (valid) {
            Docent docent = new Docent(voornaam, tussenVoegsel, achternaam, straat, huisnummer, postcode, plaats, mobiel, vast, email, rekening);
            docent.writeToDB();
            ((DefaultListModel) lijstDocenten.getModel()).addElement(docent);
        }
    }

    private void fillSelecteerDocentList() {
        DefaultListModel dml = new DefaultListModel();
        ArrayList<Docent> docenten = getDocenten();
        dml.addElement("--Nieuwe Docent--");
        for (Docent docent : docenten) {
            dml.addElement(docent);
        }
        lijstDocenten.setModel(dml);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField docentAchternaamField;
    private javax.swing.JTextField docentEmailField;
    private javax.swing.JTextField docentHuisnummerField;
    private javax.swing.JTextField docentMobielField;
    private javax.swing.JTextField docentPlaatsField;
    private javax.swing.JTextField docentPostcodeField;
    private javax.swing.JTextField docentRekeningField;
    private javax.swing.JTextField docentStraatField;
    private javax.swing.JButton docentToevoegButton;
    private javax.swing.JTextField docentTussenVoegselField;
    private javax.swing.JTextField docentVastField;
    private javax.swing.JTextField docentVoornaamField;
    private javax.swing.JButton docentWijzigButton;
    private javax.swing.JButton docentZoekButton;
    private javax.swing.JComboBox docentZoekCombo;
    private javax.swing.JTextField docentZoekField1;
    private javax.swing.JTextField docentZoekField2;
    private javax.swing.JTextField docentZoekField3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList lijstDocenten;
    // End of variables declaration//GEN-END:variables
}
