/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bart
 */
public class GUI extends javax.swing.JFrame {

    private Docent curDocent;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel39 = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        docentenTab1 = new DocentenTab();
        masterClassTab1 = new MasterClassTab();
        toernooiTab1 = new ToernooiTab();
        spelerTab1 = new SpelerTab();
        gaandeToernooienTab1 = new GaandeToernooienTab();

        jLabel39.setText("jLabel39");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });
        tabPane.addTab("Docenten", docentenTab1);
        tabPane.addTab("Masterclassen", masterClassTab1);
        tabPane.addTab("Toernooien", toernooiTab1);
        tabPane.addTab("Spelers", spelerTab1);
        tabPane.addTab("Gaande Toernooien", gaandeToernooienTab1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        Object selectedTab = tabPane.getSelectedComponent();
        if(selectedTab == docentenTab1){
            docentenTab1.refresh();
        }else if(selectedTab == masterClassTab1){
            masterClassTab1.refresh();
        }else if(selectedTab == toernooiTab1){
            toernooiTab1.refresh();
        }else if(selectedTab == spelerTab1){
            spelerTab1.refresh();
        }
            
    }//GEN-LAST:event_tabPaneStateChanged


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private DocentenTab docentenTab1;
    private GaandeToernooienTab gaandeToernooienTab1;
    private javax.swing.JLabel jLabel39;
    private MasterClassTab masterClassTab1;
    private SpelerTab spelerTab1;
    private javax.swing.JTabbedPane tabPane;
    private ToernooiTab toernooiTab1;
    // End of variables declaration//GEN-END:variables

}
